-- Sequence for Block entity
CREATE SEQUENCE block_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

-- Sequence for Transaction entity
CREATE SEQUENCE transaction_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

-- Sequence for Withdrawal entity
CREATE SEQUENCE withdrawal_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

-- Sequence for SystemSett entity
CREATE SEQUENCE system_sett_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
